/**
 * lib/post-mortem-backend.ts
 *
 * Two small helpers used only by app/api/event/list/[eventId]/post-mortem/route.ts
 * to talk to spotix-backend's internal-only post-mortem routes. Same
 * CRON_SECRET / NEXT_PUBLIC_BACKEND_URL convention as lib/payout-backend.ts's
 * triggerPayoutProcessing — reused here as the general "trusted internal
 * Spotix service" secret, not re-invented.
 *
 * Unlike triggerPayoutProcessing, these ARE awaited by the caller: the
 * booker route needs to know right away whether generation actually
 * started, already exists, or is ready, so it can tell the dialog which
 * screen to show.
 */

export interface PostMortemRequestedBy {
  uid: string
  email: string
  username?: string
  fullName?: string
}

export interface PostMortemStatusResult {
  success: boolean
  status: "none" | "processing" | "ready" | "failed"
  downloadUrl?: string | null
  generatedAt?: string | null
  /** Uid of whoever triggered generation — used server-side by the route
   *  to decide whether to show "Generated by You" instead of their name.
   *  Never forwarded to the client as-is. */
  requestedByUid?: string | null
  requestedByName?: string | null
  error?: string
}

export interface PostMortemGenerateResult {
  success: boolean
  status: "processing" | "ready" | "failed"
  started?: boolean
  alreadyExists?: boolean
  error?: string
}

function backendConfig() {
  const backendUrl = process.env.NEXT_PUBLIC_BACKEND_URL
  const secret = process.env.CRON_SECRET
  if (!backendUrl || !secret) {
    throw new Error("NEXT_PUBLIC_BACKEND_URL or CRON_SECRET missing — cannot reach spotix-backend")
  }
  return { backendUrl, secret }
}

export async function triggerPostMortemGeneration(params: {
  eventId: string
  eventName: string
  requestedBy: PostMortemRequestedBy
}): Promise<PostMortemGenerateResult> {
  const { backendUrl, secret } = backendConfig()

  const res = await fetch(`${backendUrl}/v1/post-mortem/generate`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-internal-secret": secret,
    },
    body: JSON.stringify(params),
  })

  const data = await res.json().catch(() => ({}))
  if (!res.ok && res.status !== 202) {
    return { success: false, status: "failed", error: data?.error ?? `Backend returned ${res.status}` }
  }
  return data as PostMortemGenerateResult
}

export async function getPostMortemStatus(eventId: string): Promise<PostMortemStatusResult> {
  const { backendUrl, secret } = backendConfig()

  const res = await fetch(`${backendUrl}/v1/post-mortem/status?eventId=${encodeURIComponent(eventId)}`, {
    headers: { "x-internal-secret": secret },
    cache: "no-store",
  })

  const data = await res.json().catch(() => ({}))
  if (!res.ok) {
    return { success: false, status: "failed", error: data?.error ?? `Backend returned ${res.status}` }
  }
  return data as PostMortemStatusResult
}
