/**
 * app/api/revenue/route.ts
 *
 * GET /api/revenue?userId=xxx
 *
 * Dashboard stats for a booker. Two parallel reads:
 *
 *  1. users/{userId}
 *     Reads totalEvents, ticketsSold, totalRevenue, totalPaidOut directly.
 *     availableBalance = totalRevenue - totalPaidOut (computed here, not stored).
 *
 *  2. events collection (flat)
 *     Queries where organizerId == userId.
 *     Counts how many have status "active" vs "inactive".
 *     Returns the 5 most recent events for the Recent Events table, and a
 *     revenue/tickets time series bucketed by day (14d) / month (12mo) /
 *     year (5y) — built from the same events read, no extra Firestore hit.
 *
 *     Note: each event only stores an aggregate totalRevenue (no per-day
 *     transaction ledger is available here), so the time series buckets by
 *     each event's eventDate — i.e. "revenue generated by events happening
 *     in this period", not literally "money that arrived on this calendar
 *     day". That distinction is preserved in the response shape/labels
 *     rather than faked as transaction-level granularity.
 *
 * This replaces the old nested events/{userId}/userEvents subcollection approach.
 */

import { adminDb } from "@/lib/firebase-admin"
import { verifyAccessToken } from "@/lib/auth-tokens"
import { type NextRequest, NextResponse } from "next/server"

export const runtime = "nodejs"
export const dynamic = "force-dynamic"

interface SeriesPoint {
  label: string
  date: string
  revenue: number
  ticketsSold: number
}

function buildDailySeries(events: { eventDate?: string; revenue: number; ticketsSold: number }[]): SeriesPoint[] {
  const days = 14
  const buckets = new Map<string, SeriesPoint>()
  const today = new Date()
  today.setHours(0, 0, 0, 0)

  for (let i = days - 1; i >= 0; i--) {
    const d = new Date(today)
    d.setDate(d.getDate() - i)
    const key = d.toISOString().slice(0, 10)
    buckets.set(key, {
      label: d.toLocaleDateString("en-US", { day: "2-digit" }),
      date: key,
      revenue: 0,
      ticketsSold: 0,
    })
  }

  for (const e of events) {
    if (!e.eventDate) continue
    const key = new Date(e.eventDate).toISOString().slice(0, 10)
    const bucket = buckets.get(key)
    if (bucket) {
      bucket.revenue += e.revenue
      bucket.ticketsSold += e.ticketsSold
    }
  }

  return Array.from(buckets.values())
}

function buildMonthlySeries(events: { eventDate?: string; revenue: number; ticketsSold: number }[]): SeriesPoint[] {
  const months = 12
  const buckets = new Map<string, SeriesPoint>()
  const now = new Date()

  for (let i = months - 1; i >= 0; i--) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1)
    const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`
    buckets.set(key, {
      label: d.toLocaleDateString("en-US", { month: "short" }),
      date: key,
      revenue: 0,
      ticketsSold: 0,
    })
  }

  for (const e of events) {
    if (!e.eventDate) continue
    const d = new Date(e.eventDate)
    const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`
    const bucket = buckets.get(key)
    if (bucket) {
      bucket.revenue += e.revenue
      bucket.ticketsSold += e.ticketsSold
    }
  }

  return Array.from(buckets.values())
}

function buildYearlySeries(events: { eventDate?: string; revenue: number; ticketsSold: number }[]): SeriesPoint[] {
  const years = 5
  const buckets = new Map<string, SeriesPoint>()
  const currentYear = new Date().getFullYear()

  for (let i = years - 1; i >= 0; i--) {
    const y = currentYear - i
    buckets.set(String(y), { label: String(y), date: String(y), revenue: 0, ticketsSold: 0 })
  }

  for (const e of events) {
    if (!e.eventDate) continue
    const y = String(new Date(e.eventDate).getFullYear())
    const bucket = buckets.get(y)
    if (bucket) {
      bucket.revenue += e.revenue
      bucket.ticketsSold += e.ticketsSold
    }
  }

  return Array.from(buckets.values())
}

export async function GET(request: NextRequest) {
  try {
    // Resolve user ID from middleware header or cookie fallback
    let xUserId = request.headers.get("x-user-id")
    if (!xUserId) {
      const token = request.cookies.get("spotix_at")?.value
      if (!token) {
        return NextResponse.json(
          { error: "Unauthorized", message: "Not authenticated" },
          { status: 401 }
        )
      }
      try {
        const payload = await verifyAccessToken(token, "spotix-booker")
        xUserId = payload.uid
      } catch {
        return NextResponse.json(
          { error: "Unauthorized", message: "Invalid or expired token" },
          { status: 401 }
        )
      }
    }

    const userId = request.nextUrl.searchParams.get("userId")

    if (!userId) {
      return NextResponse.json({ error: "userId is required" }, { status: 400 })
    }

    // Ensure the requesting user matches the requested userId (prevent cross-user data access)
    if (xUserId !== userId) {
      console.warn(`[api/revenue] User ${xUserId} attempted to access data for ${userId}`)
      return NextResponse.json(
        { error: "Forbidden", message: "You can only access your own data" },
        { status: 403 }
      )
    }

    // ── 1. Read aggregated stats from the user document ───────────────────────
    const userDoc = await adminDb.collection("users").doc(userId).get()

    if (!userDoc.exists) {
      return NextResponse.json({ error: "User not found" }, { status: 404 })
    }

    const userData = userDoc.data()!
    const userName = userData.username || userData.fullName || "Booker"

    const totalEvents: number = userData.totalEvents ?? 0
    const ticketsSold: number = userData.totalTicketsSold ?? 0
    const totalRevenue: number = userData.totalRevenue ?? 0
    const totalPaidOut: number = userData.totalPaidOut ?? 0
    const availableBalance: number = totalRevenue - totalPaidOut

    // ── 2. Query flat events collection by organizerId ────────────────────────
    const eventsSnap = await adminDb
      .collection("events")
      .where("organizerId", "==", userId)
      .orderBy("createdAt", "desc")
      .get()

    let activeEvents = 0
    let inactiveEvents = 0
    const recentEventsData: any[] = []
    const seriesInput: { eventDate?: string; revenue: number; ticketsSold: number }[] = []

    for (const doc of eventsSnap.docs) {
      const d = doc.data()

      if (d.status === "active") activeEvents++
      else if (d.status === "inactive") inactiveEvents++

      const revenue = d.totalRevenue || 0
      const ticketsSoldForEvent = d.ticketsSold || 0

      recentEventsData.push({
        id: doc.id,
        eventName: d.eventName || "Unnamed Event",
        eventDate: d.eventDate,
        ticketsSold: ticketsSoldForEvent,
        revenue,
        availableBalance: d.availableRevenue ?? revenue - (d.totalPaidOut || 0),
        status: d.status || "inactive",
      })

      seriesInput.push({ eventDate: d.eventDate, revenue, ticketsSold: ticketsSoldForEvent })
    }

    const recentEvents = recentEventsData.slice(0, 5)

    const timeSeries = {
      daily: buildDailySeries(seriesInput),
      monthly: buildMonthlySeries(seriesInput),
      yearly: buildYearlySeries(seriesInput),
    }

    return NextResponse.json({
      stats: {
        totalEvents,
        activeEvents,
        inactiveEvents,
        totalRevenue,
        availableBalance,
        totalPaidOut,
        totalTicketsSold: ticketsSold,
      },
      recentEvents,
      timeSeries,
      bookerName: userName,
      lastUpdated: Date.now(),
    })
  } catch (error) {
    console.error("Error fetching revenue data:", error)
    return NextResponse.json({ error: "Failed to fetch revenue data" }, { status: 500 })
  }
}
