import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Spotix Booker",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/xmas.png",
        media: "(prefers-color-scheme: light)",
      },
      {
        url: "/xmas.png",
        media: "(prefers-color-scheme: dark)",
      },
      {
        url: "/xmas.png",
        type: "image/png",
      },
    ],
    apple: "/xmas.png",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {children}
      </body>
    </html>
  );
}
