/**
 * app/api/event/list/[eventId]/post-mortem/route.ts
 *
 * GET  /api/event/list/[eventId]/post-mortem
 *   → proxies spotix-backend's status check. Used both for the dialog's
 *     initial "has this already been generated" check and for polling
 *     while a report is being computed.
 *
 * POST /api/event/list/[eventId]/post-mortem
 *   → validates access + that the event has actually ended, then hands
 *     off to spotix-backend to do the real work (Firestore read, PDF
 *     render, Supabase Storage upload, email). The one-report-per-event
 *     rule is enforced backend-side (event_id is a DB primary key there);
 *     this route's own "has the event ended" check is what stops someone
 *     from even attempting it early.
 *
 * Auth: same spotix_at cookie + resolveEventAccess as the rest of
 * event-info — owner, Admin, or any collaborator role whose tab set
 * includes "attendees" (same gate the existing registry export uses).
 */

import { NextRequest, NextResponse } from "next/server"
import { cookies } from "next/headers"
import { verifyAccessToken } from "@/lib/auth-tokens"
import { resolveEventAccess, hasTab } from "@/lib/event-access"
import { adminDb } from "@/lib/firebase-admin"
import { triggerPostMortemGeneration, getPostMortemStatus } from "@/lib/post-mortem-backend"

const DEV_TAG = "spotix-api-v1"

/** Own-domain download URL for an event's post mortem report — never the
 *  raw Supabase signed URL spotix-backend mints internally. See
 *  post-mortem/download/route.ts, same pattern as
 *  /api/polls/[pollId]/results/download. */
function buildDownloadUrl(eventId: string): string {
  return `/api/event/list/${eventId}/post-mortem/download`
}

function ok(data: object, status = 200) {
  return NextResponse.json({ success: true, developer: DEV_TAG, ...data }, { status })
}

function fail(message: string, status: number) {
  return NextResponse.json({ success: false, error: message, developer: DEV_TAG }, { status })
}

async function authenticate(): Promise<{ userId: string } | NextResponse> {
  const cookieStore = await cookies()
  const token = cookieStore.get("spotix_at")?.value
  if (!token) return fail("No access token", 401)
  try {
    const payload = await verifyAccessToken(token, "spotix-booker")
    return { userId: payload.uid }
  } catch {
    return fail("Invalid or expired access token", 401)
  }
}

export async function GET(req: NextRequest, { params }: { params: Promise<{ eventId: string }> }) {
  const auth = await authenticate()
  if (auth instanceof NextResponse) return auth
  const { userId } = auth

  const { eventId } = await params
  if (!eventId?.trim()) return fail("eventId is required", 400)

  const access = await resolveEventAccess(eventId, userId)
  if (!access.ok) return fail(access.error, access.status)
  if (!hasTab(access, "attendees")) {
    return fail("Forbidden: you do not have access to this event's attendees", 403)
  }

  try {
    const status = await getPostMortemStatus(eventId)

    if (status.status === "ready") {
      // requestedByUid never leaves this route — it's only here to decide
      // whether the viewer is the one who generated the report, so the
      // dialog can say "Generated by You" instead of their own name/email
      // staring back at them. downloadUrl is swapped for our own-domain
      // proxy route instead of spotix-backend's raw Supabase signed URL.
      const isRequester = !!status.requestedByUid && status.requestedByUid === userId
      return ok({
        status: status.status,
        downloadUrl: buildDownloadUrl(eventId),
        generatedAt: status.generatedAt,
        requestedByName: isRequester ? "You" : status.requestedByName ?? null,
      })
    }

    return ok(status)
  } catch (e: any) {
    console.error("[GET post-mortem] status check failed", e)
    return fail("Failed to check post mortem status", 500)
  }
}

export async function POST(req: NextRequest, { params }: { params: Promise<{ eventId: string }> }) {
  const auth = await authenticate()
  if (auth instanceof NextResponse) return auth
  const { userId } = auth

  const { eventId } = await params
  if (!eventId?.trim()) return fail("eventId is required", 400)

  const access = await resolveEventAccess(eventId, userId)
  if (!access.ok) return fail(access.error, access.status)
  if (!hasTab(access, "attendees")) {
    return fail("Forbidden: you do not have access to this event's attendees", 403)
  }

  const ev = access.eventSnap.data() ?? {}
  const eventName = ev.eventName ?? "Untitled Event"
  const eventEndDate = ev.eventEndDate ?? ""
  const eventEnd = ev.eventEnd ?? ""

  const end = new Date(`${eventEndDate}T${eventEnd}`)
  if (isNaN(end.getTime()) || Date.now() < end.getTime()) {
    return fail("The post mortem can only be generated after the event has ended", 400)
  }

  let requestedBy: { uid: string; email: string; username?: string; fullName?: string }
  try {
    const userDoc = await adminDb.collection("users").doc(userId).get()
    const userData = userDoc.exists ? userDoc.data()! : {}
    requestedBy = {
      uid: userId,
      email: userData.email ?? "",
      username: userData.username ?? "",
      fullName: userData.fullName ?? "",
    }
    if (!requestedBy.email) return fail("Your account has no email on file", 400)
  } catch (e: any) {
    console.error("[POST post-mortem] failed to load requester profile", e)
    return fail("Failed to load your profile", 500)
  }

  try {
    const result = await triggerPostMortemGeneration({ eventId, eventName, requestedBy })
    return ok(result)
  } catch (e: any) {
    console.error("[POST post-mortem] trigger failed", e)
    return fail("Failed to start post mortem generation", 500)
  }
}
